'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SportsManagement.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property cricket1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cricket1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cricket2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cricket2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cricket3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cricket3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property football1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property football2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property football22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property football24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property football3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property football4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property football5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property football55() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("football55", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hockey1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hockey1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hockey2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hockey2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LoadingAnimation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadingAnimation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Login_Icon4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Login-Icon4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property system_lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("system_lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tennis1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tennis1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tennis14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tennis14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tennis2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tennis2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property volley1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volley1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property volley11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volley11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property volley2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volley2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property volley20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volley20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property volley21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volley21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
